database:
  type: "mysql" #h2, mysql, postgresql,
  host: "test"
  port: "3306"
  database: "test"
  username: "test"
  password: "test"
  table-prefix: "test"
communication:
  mode: "plugin_message" #plugin_message, rabbitmq
  
features:
  base:
    enabled: true
    permissions:
      reload: test.reload